if(NOT DEFINED CLI)
  message(FATAL_ERROR "CLI executable path is required")
endif()
string(RANDOM LENGTH 12 run_id)
set(root "${CMAKE_CURRENT_BINARY_DIR}/continuum-cli-${run_id}")
file(MAKE_DIRECTORY "${root}")
function(reject expected)
  execute_process(COMMAND "${CLI}" color cool-continuum ${ARGN}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(status EQUAL 0 OR NOT "${output}${error}" MATCHES "${expected}")
    message(FATAL_ERROR "Expected ${expected}: ${status} ${output} ${error}")
  endif()
endfunction()
foreach(value nan inf -0.01 0.121 0.06garbage)
  reject(ArgumentInvalid --input "${root}/missing.tiff" --output "${root}/output.tiff" --amount "${value}")
endforeach()
foreach(value 0 3 65 4.5 -1 4294967296)
  reject(ArgumentInvalid --input "${root}/missing.tiff" --output "${root}/output.tiff" --radius "${value}")
endforeach()
reject(ArgumentMissing --input)
reject(ArgumentMissing --radius)
reject(ArgumentMissing --estimator)
reject(ArgumentInvalid --input "${root}/missing.tiff" --output "${root}/output.tiff" --estimator unknown)
reject(ArgumentInvalid --unknown 2)
reject(ArgumentInvalid --input "${root}/raw.fits" --output "${root}/out.tiff")
reject(ArgumentInvalid --input "${root}/image.tiff" --output "${root}/out.fit")
file(WRITE "${root}/input.tiff" "input must stay intact")
file(SHA256 "${root}/input.tiff" before)
file(CREATE_LINK "${root}/input.tiff" "${root}/hard.tiff" RESULT link_result)
if(NOT link_result STREQUAL "0")
  message(FATAL_ERROR "Could not create hardlink fixture: ${link_result}")
endif()
file(CREATE_LINK "${root}/input.tiff" "${root}/symbolic.tiff" SYMBOLIC)
foreach(output input.tiff hard.tiff symbolic.tiff)
  reject(OutputConflictsWithInput --input "${root}/input.tiff" --output "${root}/${output}")
endforeach()
file(SHA256 "${root}/input.tiff" after)
if(NOT before STREQUAL after OR EXISTS "${root}/output.tiff")
  message(FATAL_ERROR "Rejected operations modified an image")
endif()
file(REMOVE_RECURSE "${root}")
