if(NOT DEFINED CLI)
  message(FATAL_ERROR "CLI executable path is required")
endif()
string(RANDOM LENGTH 12 run_id)
set(root "${CMAKE_CURRENT_BINARY_DIR}/display-grid-${run_id}")
file(MAKE_DIRECTORY "${root}")
function(reject expected)
  execute_process(COMMAND "${CLI}" suppress-grid ${ARGN}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(status EQUAL 0 OR NOT "${output}${error}" MATCHES "${expected}")
    message(FATAL_ERROR "Expected ${expected}: ${status} ${output} ${error}")
  endif()
endfunction()
foreach(value nan inf -0.01 1.001 0.5garbage)
  reject(ArgumentInvalid --input "${root}/missing.tiff" --output "${root}/output.tiff" --amount "${value}")
endforeach()
reject(ArgumentMissing --input)
reject(ArgumentMissing --amount)
reject(ArgumentMissing --input "${root}/missing.tiff")
reject(ArgumentInvalid --unknown 2)
reject(ArgumentInvalid --input "${root}/raw.fits" --output "${root}/out.tiff")
reject(ArgumentInvalid --input "${root}/image.tiff" --output "${root}/out.fit")
reject(ArgumentInvalid --input "${root}/raw.dng" --output "${root}/out.tiff")
file(WRITE "${root}/input.tiff" "source must stay intact")
file(WRITE "${root}/out.tiff" "existing result must stay intact")
file(SHA256 "${root}/input.tiff" input_before)
file(SHA256 "${root}/out.tiff" output_before)
file(CREATE_LINK "${root}/input.tiff" "${root}/hard.tiff" RESULT linked)
if(NOT linked STREQUAL "0")
  message(FATAL_ERROR "Could not create hardlink fixture: ${linked}")
endif()
file(CREATE_LINK "${root}/input.tiff" "${root}/symbolic.tiff" SYMBOLIC)
file(CREATE_LINK "${root}/absent.tiff" "${root}/dangling.tiff" SYMBOLIC)
foreach(output input.tiff out.tiff hard.tiff symbolic.tiff dangling.tiff)
  reject(OutputExists --input "${root}/input.tiff" --output "${root}/${output}")
endforeach()
file(SHA256 "${root}/input.tiff" input_after)
file(SHA256 "${root}/out.tiff" output_after)
if(NOT input_before STREQUAL input_after OR NOT output_before STREQUAL output_after
   OR EXISTS "${root}/output.tiff" OR EXISTS "${root}/absent.tiff")
  message(FATAL_ERROR "Rejected operations changed a file")
endif()
file(REMOVE_RECURSE "${root}")
