if(NOT DEFINED CLI)
  message(FATAL_ERROR "CLI executable path is required")
endif()
string(RANDOM LENGTH 12 run_id)
set(root "${CMAKE_CURRENT_BINARY_DIR}/nonlocal-cli-${run_id}")
file(MAKE_DIRECTORY "${root}")

function(fixture path width height channels offset payload)
  set(cards "SIMPLE  = T" "BITPIX  = 8" "NAXIS   = 3" "NAXIS1  = ${width}"
    "NAXIS2  = ${height}" "NAXIS3  = ${channels}" "BZERO   = ${offset}" "END")
  set(header "")
  foreach(card IN LISTS cards)
    string(LENGTH "${card}" n)
    math(EXPR n "80 - ${n}")
    string(REPEAT " " ${n} padding)
    string(APPEND header "${card}${padding}")
  endforeach()
  string(LENGTH "${header}" n)
  math(EXPR n "2880 - ${n}")
  string(REPEAT " " ${n} padding)
  string(APPEND header "${padding}")
  string(LENGTH "${payload}" n)
  math(EXPR n "2880 - ${n}")
  string(REPEAT " " ${n} padding)
  file(WRITE "${path}" "${header}${payload}${padding}")
endfunction()
fixture("${root}/input.fits" 3 2 3 -100 "0123456789ABCDEFGH")
fixture("${root}/mask.fits" 3 2 1 -48 "111111")
fixture("${root}/bad-mask.fits" 3 2 1 -50 "111111")
fixture("${root}/wrong-size.fits" 2 2 1 -48 "1111")

function(run_case expected message)
  execute_process(COMMAND "${CLI}" denoise-nonlocal ${ARGN}
    RESULT_VARIABLE status OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
  if(expected STREQUAL "success")
    if(NOT status EQUAL 0)
      message(FATAL_ERROR "Expected success: ${stdout}${stderr}")
    endif()
  elseif(status EQUAL 0)
    message(FATAL_ERROR "Unexpected success: ${ARGN}")
  endif()
  string(FIND "${stdout}${stderr}" "${message}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "Expected ${message}: ${stdout}${stderr}")
  endif()
endfunction()
set(input --input "${root}/input.fits")
set(mask --blend-map "${root}/mask.fits")
run_case(success "\"clampOutput\": false" ${input} ${mask} --h 10 --output "${root}/out.fits")
run_case(success "\"mode\": \"conservative-rgb\"" ${input} ${mask} --h 10 --mode conservative-rgb --output "${root}/conservative.fits")
run_case(success "\"mode\": \"luminance\"" ${input} ${mask} --h 10 --mode luminance --output "${root}/explicit-default.fits")
file(SHA256 "${root}/out.fits" default_hash)
file(SHA256 "${root}/explicit-default.fits" explicit_hash)
if(NOT default_hash STREQUAL explicit_hash)
  message(FATAL_ERROR "Explicit default mode changes output")
endif()
run_case(failure "ArgumentInvalid" ${input} ${mask} --h 10 --mode unknown --output "${root}/mode-out.fits")
run_case(failure "ArgumentMissing" ${input} ${mask} --h 10 --output "${root}/missing-mode-out.fits" --mode)
if(NOT EXISTS "${root}/out.fits")
  message(FATAL_ERROR "No FITS output")
endif()
file(SHA256 "${root}/input.fits" original)
file(SHA256 "${root}/out.fits" produced)
run_case(failure "OutputExists" ${input} ${mask} --h 10 --output "${root}/out.fits")
run_case(failure "OutputExists" ${input} ${mask} --h 10 --output "${root}/input.fits")
run_case(failure "OutputExists" ${input} ${mask} --h 10 --output "${root}/mask.fits")
file(SHA256 "${root}/input.fits" after)
file(SHA256 "${root}/out.fits" output_after)
if(NOT original STREQUAL after OR NOT produced STREQUAL output_after)
  message(FATAL_ERROR "Existing data changed")
endif()
file(CREATE_LINK "${root}/does-not-exist.fits" "${root}/link.fits" SYMBOLIC)
run_case(failure "OutputExists" ${input} ${mask} --h 10 --output "${root}/link.fits")
run_case(failure "not CFA or grayscale" --input "${root}/mask.fits" ${mask} --h 10 --output "${root}/mono-out.fits")
run_case(failure "matching dimensions" ${input} --blend-map "${root}/wrong-size.fits" --h 10 --output "${root}/size-out.fits")
run_case(failure "weights in [0,1]" ${input} --blend-map "${root}/bad-mask.fits" --h 10 --output "${root}/range-out.fits")
run_case(failure "explicit --h" ${input} ${mask} --output "${root}/unspecified-out.fits")
foreach(name mono-out size-out range-out unspecified-out does-not-exist mode-out missing-mode-out)
  if(EXISTS "${root}/${name}.fits")
    message(FATAL_ERROR "Rejected command wrote ${name}")
  endif()
endforeach()
file(REMOVE_RECURSE "${root}")
