if(NOT DEFINED CLI)
  message(FATAL_ERROR "CLI executable path is required")
endif()
string(RANDOM LENGTH 12 run_id)
set(root "${CMAKE_CURRENT_BINARY_DIR}/review-preview-${run_id}")
file(MAKE_DIRECTORY "${root}")
function(reject expected)
  execute_process(COMMAND "${CLI}" review-preview ${ARGN}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(status EQUAL 0 OR NOT "${output}${error}" MATCHES "${expected}")
    message(FATAL_ERROR "Expected ${expected}: ${status} ${output} ${error}")
  endif()
endfunction()
reject(ArgumentMissing --input)
reject(ArgumentMissing --input "${root}/missing.fit")
reject(ArgumentInvalid --unknown 2)
reject(ArgumentInvalid --input x --output "${root}/out.jpg")
reject(ArgumentInvalid --fits-debayer invalid)
reject(ArgumentInvalid --fits-demosaic invalid)
file(WRITE "${root}/input.tiff" "source must stay intact")
file(SHA256 "${root}/input.tiff" before)
file(CREATE_LINK "${root}/input.tiff" "${root}/hard.tiff")
file(CREATE_LINK "${root}/absent.tiff" "${root}/dangling.tiff" SYMBOLIC)
foreach(output input.tiff hard.tiff dangling.tiff)
  reject(OutputExists --input "${root}/input.tiff" --output "${root}/${output}")
endforeach()
file(SHA256 "${root}/input.tiff" after)
if(NOT before STREQUAL after OR EXISTS "${root}/absent.tiff")
  message(FATAL_ERROR "Rejected preview changed a file")
endif()
file(REMOVE_RECURSE "${root}")
